# Generated by Django 6.0.2 on 2026-02-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_name', models.CharField(max_length=100)),
                ('Dep_code', models.CharField(max_length=20, unique=True)),
                ('Dep_head', models.CharField(max_length=100)),
                ('Dep_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Contact', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=20)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
    ]
