# Generated by Django 6.0.2 on 2026-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=30)),
                ('Query', models.TextField()),
                ('Status', models.BooleanField(default='pending')),
            ],
        ),
    ]
