# Generated by Django 6.0.2 on 2026-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Confirm_Password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Age_group',
            field=models.CharField(max_length=10),
        ),
    ]
