# Generated by Django 6.0.2 on 2026-02-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='QueryData',
        ),
    ]
