# Generated by Django 6.0.2 on 2026-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_confirm_password_alter_employee_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Confirm_Password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=8),
        ),
    ]
