# Generated by Django 6.0.2 on 2026-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_query_querydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryData',
            new_name='Empquery',
        ),
    ]
