# Generated by Django 6.0.2 on 2026-02-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_querydata_empquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empquery',
            name='Status',
            field=models.CharField(default='pending'),
        ),
    ]
